table sedef_chm13 "SedDups Features Description"
(
string  chrom;		"Reference sequence chromosome or scaffold"
uint    chromStart;	"Transcription start position"
uint    chromEnd;		"Transcription end position"
string  name;		"Name of gene"
uint    score;		"fake score"
char[1] strand;		"+ or - for strand"
uint    thickStart;	"Coding region start"
uint    thickEnd;		"Coding region end"
uint    color;		"Green on + strand, Red on - strand"
string  chrom2;		"Reference sequence chromosome or scaffold"
uint    Start2;     "Transcription start position"
uint    End2;		"Transcription end position"
float    score2;		"Score"
char[1] strand2;	"+ or - for strand"
uint    maxlen;     "max_len"
uint    alnlen;     "aln_len"
uint    indela;     "indel_a"
uint    indelb;     "indel_b"
uint    alnB;       "alnB"
uint    matchB;     "matchB"
uint    mismatchB;     "mismatchB"
uint    transitionsB;       "transitionsB"
uint    transvertionsB;     "transvertionsB"
float   fracMatch;          "fracMatch"
float   fracMatchIndel;     "fracMatchIndel"
float   jck;                "jck"
float   k2K;                "k2K"
uint    alngaps;            "aln_gaps"
uint    uppercaseA;         "uppercaseA"
uint    uppercaseB;         "uppercaseB"
uint    uppercaseMatches;   "uppercaseMatches"
uint    alnMatches;         "aln_matches"
uint    alnMismatches;      "aln_mismatches"
uint    alnGapBases;        "aln_gap_bases"
float   filterScore;        "filter_score"
)
